version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/python-crm  
    steps:

      - checkout
      - run: mkdir dist
      - run: pwd && cat /etc/issue  && uname -a > dist/test.html
      - run: 
         command: |
           git config --global user.name feigu1984
           git config --global user.email feigu_1984@qq.com
           git add -A && git commit -m "deploy" 
           git subtree push --prefix=dist origin gh-pages
      
workflows:
  version: 2
  commit:
    jobs:
      - build
