name: Integration Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  pre_ci:
    name: Prepare CI environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          # We need to fetch with a depth of 2 for pull_request so we can do HEAD^2
          fetch-depth: 2

      # - name: "[Push] Get commit message"
      #   if: github.event_name == 'push'
      #   id: push_get_commit_message
      #   run:
      #     echo ::set-output name=push_commit_message::$(git log --format=%B -n 1 HEAD)

      - name: "[Pull Request] Get commit message"
        if: github.event_name == 'pull_request'
        id: pr_get_commit_message
        run: echo ::set-output name=pr_commit_message::$(git log --format=%B -n 1 HEAD^2)

      - name: debug Log commit message
        run: echo "${{ steps.pr_get_commit_message.outputs.pr_commit_message }}"
    outputs:
      # commit_message: $( [ -z "${{ steps.pr_get_commit_message.outputs.pr_commit_message }}" ] && echo "${{ steps.push_get_commit_message.outputs.push_commit_message }}" || echo "${{ steps.pr_get_commit_message.outputs.pr_commit_message }}" )
      commit_message: $( [ -z "${{ steps.pr_get_commit_message.outputs.pr_commit_message }}" ] && echo "${{ steps.pr_get_commit_message.outputs.pr_commit_message }}" )

  able_job:
    name: Runtest Job
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, kuang]
    if: "contains(needs.pre_ci.outputs.commit_message, 'runtest')"
    needs: pre_ci
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

        # If this job doesn't get skipped you'll see the commit message appear here, it's just a debugging this
        # so be sure to remove it for your actual workflow
      - name: Log commit message
        run: echo "${{ needs.pre_ci.outputs.commit_message }}"
