name: feiren test
# This workflow is triggered on pushes to the repository.
#on: [push]
on:
  push:
    branches:
      - master
    tags:
      - v1
    # 事件中要考虑的文件路径。 Optional; defaults to all.
    paths:
      - 'test/*'

jobs:
  build:
    # 作业名称为 Greeting
    name: Greeting
    # 此作业在 Linux 上运行
    runs-on: ubuntu-latest
    env:
      keyword: ${{ secrts.PR_CM_KEYWORD }}
    #runs-on: ${{ matrix.os }}
    #  strategy:
    #    matrix:
    #      os: [ubuntu-16.04, ubuntu-18.04]
    #      node: [6, 8, 10]
    steps:
      # 此步骤使用 GitHub 的 hello-world-javascript-action：https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # 此步骤打印上一步操作的输出（时间）。
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
      - name: Echo the Keyword
        run: echo "The secrts: keyword: ${keyword}"


